name: Release

on: # yamllint disable-line rule:truthy
  push:
    tags:
    - v*

permissions:
  contents: write

jobs:
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Fetch tags
      run: git fetch --force --tags
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version-file: .go-version
        cache: true
    - uses: goreleaser/goreleaser-action@v4
      with:
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
